# Generated by Django 3.2.4 on 2021-06-17 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_section'),
        ('product', '0002_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=255, null=True)),
                ('main_image', models.ImageField(help_text='This is the default image of the product... It would be prioritized over other images', upload_to='images')),
                ('thumbnail', models.ImageField(blank=True, help_text='This is the smaller version of the main image. It would be autogenerated', null=True, upload_to='thumbnail')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.category')),
                ('section', models.ManyToManyField(blank=True, null=True, related_name='products', to='core.Section')),
            ],
        ),
    ]
