# Generated by Django 3.2.4 on 2021-06-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_section'),
        ('product', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='section',
            field=models.ManyToManyField(related_name='products', to='core.Section'),
        ),
    ]
