# Generated by Django 3.2.4 on 2021-06-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_section'),
        ('product', '0006_auto_20210617_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='section',
            field=models.ManyToManyField(blank=True, related_name='products', to='core.Section'),
        ),
    ]
