# Generated by Django 3.2.4 on 2021-06-23 09:36

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(help_text='This is the image that represents this category.', storage=gdstorage.storage.GoogleDriveStorage(), upload_to='images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(help_text='This is the default image of the product... It would be prioritized over other images', storage=gdstorage.storage.GoogleDriveStorage(), upload_to='images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='This is the smaller version of the main image. It would be autogenerated', null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='thumbnail'),
        ),
    ]
