# Generated by Django 3.2.4 on 2021-06-16 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the category', max_length=255)),
                ('slug', models.SlugField(help_text='This is the slug field of the category. It would be appended to the url e.g "https://www.example.com/categories/category-slug"', max_length=255)),
                ('image', models.ImageField(help_text='This is the image that represents this category.', upload_to='images')),
                ('image_alt', models.CharField(blank=True, help_text='This would show whenever the image refuses to display', max_length=500, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category')),
            ],
        ),
    ]
