# Generated by Django 3.2.4 on 2021-06-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0002_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
                ('store_tagline', models.CharField(help_text='This is the tagline of the store. Optional!', max_length=500)),
                ('store_logo', models.ImageField(upload_to='settings')),
                ('favicon', models.ImageField(blank=True, help_text='This is the icon that would be shown on the title bar of the browser', null=True, upload_to='settings')),
                ('store_phone_number', models.CharField(help_text='The contact phone number for the store', max_length=20)),
                ('store_email', models.CharField(help_text='The contact email of the store', max_length=80)),
                ('store_address', models.TextField(help_text='The address the store is located at', null=True)),
                ('copyright_text', models.CharField(blank=True, help_text='This is the copyright text that would be shown in the footer of your store', max_length=500, null=True)),
                ('facebook_url', models.CharField(help_text='The link to the facebook account of the store', max_length=500, null=True)),
                ('instagram_url', models.CharField(help_text='The link to the facebook account of the store', max_length=500, null=True)),
                ('twitter_url', models.CharField(help_text='The link to the facebook account of the store', max_length=500, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='This is the description of the store that would be showm on search engines', null=True)),
                ('keywords', models.CharField(blank=True, help_text='This are the keywords that relaes with the store and it should be seperated be commas e.g clothes, summer, trouser', max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Store Settings',
            },
        ),
    ]
