# Generated by Django 3.2.4 on 2021-06-25 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210623_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='The code that represents the currency e.g NGN, USD', max_length=5)),
                ('exchange_rate', models.DecimalField(decimal_places=2, help_text='The rate of the currency compared to USD', max_digits=19)),
                ('symbol', models.CharField(blank=True, help_text='Optional. The sign that represents the currency e.g $, If not specified the currency code would be used instead.', max_length=3, null=True)),
                ('position', models.CharField(blank=True, choices=[('right', 'Right'), ('left', 'Left')], default='left', help_text='Optional. Where is the currency symbol placed? Default is left', max_length=8, null=True)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the country', max_length=100)),
                ('currency', models.ForeignKey(help_text='What currency do they use in this country', on_delete=django.db.models.deletion.CASCADE, to='store.currency')),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
    ]
