# Generated by Django 3.2.4 on 2021-06-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the image', max_length=255)),
                ('alt_text', models.CharField(blank=True, help_text='This would show whenever the image refuses to show', max_length=255, null=True)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
