# Generated by Django 3.2.3 on 2021-06-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g USD, NGN', max_length=255)),
                ('symbol', models.CharField(blank=True, help_text='Optional. This is the symbol of the currency e.g $', max_length=5, null=True)),
                ('position', models.CharField(choices=[('r', 'RIGHT'), ('l', 'LEFT')], max_length=5)),
                ('exchange_rate', models.DecimalField(decimal_places=2, help_text='This is the exchange rate of the currency to dollars', max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
                ('store_tagline', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
