# Generated by Django 3.2.3 on 2021-06-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
                ('store_tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('store_logo', models.ImageField(upload_to='store')),
                ('store_address', models.TextField()),
                ('store_contact_phone_number', models.IntegerField()),
                ('store_email', models.EmailField(max_length=255)),
                ('copyright_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
