# Generated by Django 3.2.3 on 2021-06-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210608_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialIcons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the social media e.g Facebook, Twitter, Google', max_length=255)),
                ('url', models.URLField(help_text='The URL of your social media page e.g https://facebook.com/my-page', max_length=555)),
                ('icon', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='seo',
            name='favicon',
            field=models.ImageField(default='test', help_text='This is the little icon that would be shown beside your title in the browser', upload_to='store'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seo',
            name='keywords',
            field=models.TextField(default='store', help_text='This are what your stores are related with. It could be seperated with commas ","'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seo',
            name='meta_description',
            field=models.TextField(default='This is a store', help_text='This is the description that would be shown on search engines'),
            preserve_default=False,
        ),
    ]
