# Generated by Django 3.2.3 on 2021-06-08 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210608_1225'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialIcons',
            new_name='SocialIcon',
        ),
    ]
