# Generated by Django 3.2.3 on 2021-06-08 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_socialicons_socialicon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seo',
            options={'verbose_name_plural': 'SEO'},
        ),
    ]
