# Generated by Django 3.2.3 on 2021-06-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_paypal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flutterwave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('is_live', models.BooleanField()),
                ('test_public_key', models.CharField(blank=True, max_length=800, null=True)),
                ('test_private_key', models.CharField(blank=True, max_length=800, null=True)),
                ('live_public_key', models.CharField(blank=True, max_length=800, null=True)),
                ('live_private_key', models.CharField(blank=True, max_length=800, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paystack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('is_live', models.BooleanField()),
                ('test_public_key', models.CharField(blank=True, max_length=800, null=True)),
                ('test_private_key', models.CharField(blank=True, max_length=800, null=True)),
                ('live_public_key', models.CharField(blank=True, max_length=800, null=True)),
                ('live_private_key', models.CharField(blank=True, max_length=800, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stripe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('is_live', models.BooleanField()),
                ('test_public_key', models.CharField(blank=True, max_length=800, null=True)),
                ('test_private_key', models.CharField(blank=True, max_length=800, null=True)),
                ('live_public_key', models.CharField(blank=True, max_length=800, null=True)),
                ('live_private_key', models.CharField(blank=True, max_length=800, null=True)),
            ],
        ),
    ]
