# Generated by Django 3.2.3 on 2021-06-08 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210606_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='seo_title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_title',
        ),
    ]
